### ISSUE TITLE
slideOffset is Infinity or NaN

### ISSUE THREAD

**Issue by ngThu** [NikoYuwono/ToolbarPanel#2]
Many time slideOffset show is Infinity  or >1 or NaN
I don't understand.
If you have free time, please check! Thank so much!

**Comment by NikoYuwono** [comment]
@ngThu Sorry for late reply but could you tell me how to reproduce it? And tell me what environment are you working at? Thanks!

**Comment by NikoYuwono** [comment]
Closing it for now because unreproducable and need more info how to reproduce it
